services:
  mysql:
    image: mysql:5.7
    container_name: fastapi_ocr-mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastapi
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - local_network

  mongo:
    image: mongo:latest
    container_name: fastapi_ocr-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./.docker/mongo/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - local_network

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: fastapi_ocr
    volumes:
      - ./:/app
      - venv_data:/app/.venv
    ports:
      - "9093:8000"
      - "8888:8888"
    networks:
      - local_network
    environment:
      SERVICE_TYPE: app
      DB_HOST: fastapi_ocr-mysql
      MONGO_DB_HOST: fastapi_ocr-mongodb
      CELERY_BROKER_URL: redis://fastapi_ocr-redis:6379/0

  redis:
    image: redis:latest
    container_name: fastapi_ocr-redis
    ports:
      - "6379:6379"
    networks:
      - local_network

  celery:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: fastapi_ocr-celery
    volumes:
      - ./:/app
      - venv_data:/app/.venv
    networks:
      - local_network
    environment:
      SERVICE_TYPE: worker
      CELERY_BROKER_URL: redis://fastapi_ocr-redis:6379/0
      CELERY_RESULT_BACKEND: redis://fastapi_ocr-redis:6379/1
      DB_HOST: fastapi_ocr-mysql
      MONGO_DB_HOST: fastapi_ocr-mongodb

  flower:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: fastapi_ocr-flower
    volumes:
      - ./:/app
      - venv_data:/app/.venv
    ports:
      - "5555:5555"
    networks:
      - local_network
    environment:
      SERVICE_TYPE: flower
      CELERY_BROKER_URL: redis://fastapi_ocr-redis:6379/0
      CELERY_RESULT_BACKEND: redis://fastapi_ocr-redis:6379/1

volumes:
    venv_data:

networks:
  local_network:
    driver: bridge
