"""empty message

Revision ID: 656b50a64e76
Revises: 
Create Date: 2026-04-28 15:08:47.472752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '656b50a64e76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_jobs',
    sa.Column('id', sa.String(length=50), nullable=False, comment='UUID4'),
    sa.Column('status', sa.Enum('PENDING', 'STARTED', 'SUCCESS', 'FAILED', name='jobstatus'), nullable=False, comment='OCR 상태: pending | started | success | failed'),
    sa.Column('engine', sa.String(length=30), nullable=False, comment='OCR 엔진: easyocr | paddleocr | clovaocr'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='업로드 파일명'),
    sa.Column('file_path', sa.String(length=512), nullable=False, comment='업로드 파일 경로'),
    sa.Column('result', sa.JSON(), nullable=True, comment='OCR 완료 결과'),
    sa.Column('info', sa.JSON(), nullable=True, comment='OCR 실패 시 메시지, 로그'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='생성 시간'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='실행 시간'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='완료 시간'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_jobs_status'), 'ocr_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_jobs_status'), table_name='ocr_jobs')
    op.drop_table('ocr_jobs')
    # ### end Alembic commands ###
